#!/bin/sh

BASEDIR=$(dirname $(readlink -f $0))

. $BASEDIR/OneIM-Helper.inc.sh || exit 254
CONTAINER=$CONTAINERDATA/js${ONEIM}

if [ ! -d "$CONTAINER"/logs ]; then 
    mkdir -p $CONTAINER/logs
fi

$DRY podman run --rm --name js${ONEIM} \
    --add-host OneIMDB-${ONEIM}:10.0.2.2 \
    --network=slirp4netns:allow_host_loopback=true \
    -p 18${ONEIM}:1880 \
    -e "DBSYSTEM=MSSQL" \
    -e "CONNSTRING=Data Source=OneIMDB-${ONEIM},14${ONEIM};Initial Catalog=OneIM;User ID=OneIM_Admin;Password=Pass_word1"  \
    -e "SERVERNAME=OneIMDB-${ONEIM}" \
    -e "HTTP_USER=admin" \
    -e "HTTP_PWD=Pass_word1" \
    -e "REQUESTINTERVAL=30" \
    -e "QUEUE=\\OneIMDB-${ONEIM}" \
    -e "DEBUGMODE=True" \
    -v "$HOME/Progs/Containers/js${ONEIM}/logs:/var/log/jobservice" \
    oneidentity/oneim-job:$ONEIMVERSION

