#!/bin/sh

BASEDIR=$(dirname $(readlink -f $0))

. $BASEDIR/OneIM-Helper.inc.sh || exit 254

CONTAINER=${CONTAINERDATA}/api${ONEIM}
create_container_subdir_web 33 secrets

$DRY podman run --rm \
    --add-host OneIMDB-${ONEIM}:10.0.2.2 \
    --network=slirp4netns:allow_host_loopback=true \
    --name apiserver-${ONEIM} \
    -p 19${ONEIM}:${WEBPORT} \
    -e "DBSYSTEM=MSSQL" \
    -e "CONNSTRING=Data Source=OneIMDB-${ONEIM},14${ONEIM};Initial Catalog=OneIM;User ID=OneIM_Admin;Password=Pass_word1" \
    -e "UPDATEUSER=Module=DialogUser;User=viadmin;password=Pass_word1" \
    -e "APPSERVERCONNSTRING=URL=http://OneIMDB-${ONEIM}:17${ONEIM}/" \
    -e "BASEURL=http://OneIMDB-${ONEIM}:19${ONEIM}/" \
    -e "TRUSTEDSOURCEKEY=D34db33F!" \
    -e "APPLICATIONTOKEN=mytoken" \
    -e "FORCEAPPTOKEN=1" \
    -v ${CONTAINER}/secrets:/run/secrets \
    oneidentity/oneim-api:${ONEIMVERSION}

