#!/bin/sh

BASEDIR=$(dirname $(readlink -f $0))

. $BASEDIR/OneIM-Helper.inc.sh || exit 254

CONTAINER=${CONTAINERDATA}/app${ONEIM}
create_container_subdir_web 33 secrets search cache

$DRY podman run --rm \
    --add-host OneIMDB-${ONEIM}:10.0.2.2 \
    --network=slirp4netns:allow_host_loopback=true \
    --name appserver-${ONEIM} \
    -p 17${ONEIM}:${WEBPORT} \
    -e "DBSYSTEM=MSSQL" \
    -e "CONNSTRING=Data Source=OneIMDB-${ONEIM},14${ONEIM};Initial Catalog=OneIM;User ID=OneIM_Admin;Password=Pass_word1"  \
    -v ${CONTAINER}/secrets:/run/secrets \
    -v ${CONTAINER}/search:/var/search \
    -v ${CONTAINER}/cache:/var/www/App_Data/Cache \
    -d oneidentity/oneim-appserver:$ONEIMVERSION \
|| exit 1;

echo "Does not supported logging to files, use docker logs."
