#!/bin/sh

BASEDIR=$(dirname $(readlink -f $0))

. $BASEDIR/OneIM-Helper.inc.sh || exit 254

if [ "$ONEIM" -gt 92 ];then
    echo "Webdesigner web portal discontinued"
    exit 253
fi

CONTAINER=${CONTAINERDATA}/webportal${ONEIM}

# www-data uid/gid: 33
create_container_subdir_web 33 secrets cache

$DRY podman run --rm  \
    --name web${ONEIM} \
    --add-host OneIMDB-${ONEIM}:10.0.2.2 \
    --network=slirp4netns:allow_host_loopback=true \
    -p 16${ONEIM}:80 \
    -e "DBSYSTEM=MSSQL" \
    -e "CONNSTRING=Data Source=OneIMDB-${ONEIM},14${ONEIM};Initial Catalog=OneIM;User ID=OneIM_Admin;Password=Pass_word1"  \
    -e "UPDATEUSER=Module=DialogUser;User=viadmin;password=Pass_word1" \
    -e "SUBWEBAUTHSTRING=Module=DialogUser;User=viadmin;password=Pass_word1"\
    -e "REGISTRATIONUSER=Module=DialogUser;User=viadmin;password=Pass_word1" \
    -e "APPSERVERCONNSTRING=URL=http://OneIMDB-${ONEIM}:17${ONEIM}/" \
    -e "BASEURL=http://OneIMDB-${ONEIM}:16${ONEIM}/" \
    -e "TRUSTEDSOURCEKEY=D34db33F!" \
    -e "APPLICATIONTOKEN=mytoken" \
    -e "FORCEAPPTOKEN=1" \
    -v ${CONTAINER}/secrets:/run/secrets:ro \
    -v ${CONTAINER}/cache:/var/www/App_Data/Cache \
    -d oneidentity/oneim-web:$ONEIMVERSION
