#!/bin/sh

BASEDIR=$(dirname $(readlink -f $0))
ISDBSCRIPT=1

#lame
ONEIMADDR=xyz

. $BASEDIR/OneIM-Helper.inc.sh || exit 254
CONTAINER=${CONTAINERDATA}/db${ONEIM}

#UID/GID from container perspective are 10001
if [ ! -d "$CONTAINER" ]; then 
    mkdir $CONTAINER
    chmod g+ws $CONTAINER
    podman unshare chgrp 10001 $CONTAINER
fi

if [ -z "$MSSQLVERSION" ];then
    echo "No MSSQLVERSION given as parameter or MSSQLDEFAULTVERSION"
    usage
    exit 254
fi

$DRY podman run --rm --name OneIMDB-${ONEIM} --hostname OneIMDB-${ONEIM} \
    -e 'ACCEPT_EULA=Y' \
    -e 'SA_PASSWORD=Pass_word1' \
    -e 'MSSQL_PID=Developer'  \
    -e 'MSSQL_AGENT_ENABLED=True' \
    -v ${CONTAINER}:/var/opt/mssql:Z \
    -p 14${ONEIM}:1433 \
    -d mcr.microsoft.com/mssql/server:${MSSQLVERSION}-latest
